import type { CreatorManualManifest } from './schema';

export const sampleCreatorManualManifest: CreatorManualManifest = {
  schemaVersion: 'creator_manual_v1',
  template: {
    id: 'creator-manual',
    version: 1,
  },
  hubId: 'creator_manual_preview',
  releaseId: 'preview_2026_05_01',
  hubSlug: 'creator-manual-preview',
  visibility: 'unlisted',
  publishedAt: null,
  generatedAt: '2026-05-01T00:00:00.000Z',
  title: 'Creator Manual Preview',
  tagline: 'A practical operating manual for turning attention into durable work.',
  creator: {
    name: 'Preview Creator',
    handle: '@preview',
    canonicalUrl: 'https://example.com/preview-creator',
    tagline: 'Evidence-led creator systems for practical operators.',
    thesis: 'Durable creator work comes from clear positioning, repeatable capture, and visible proof.',
    about: 'Preview Creator is a sample educator and operator used to preview the Creator Manual template.',
    voiceSummary: 'Direct, practical, source-backed, and biased toward useful examples over vague inspiration.',
  },
  brand: {
    name: 'Field Manual',
    tone: 'direct, evidence-led, practical',
    tokens: {
      colors: {
        background: '#0F0F0D',
        foreground: '#F7F2E7',
        surface: '#181713',
        elevated: '#242117',
        border: '#3A3526',
        muted: '#6b7280',
        accent: '#F5C542',
        accentForeground: '#111111',
        warning: '#F97316',
        success: '#22C55E',
        typeMap: {
          principle: '#F5C542',
          playbook: '#38BDF8',
          example: '#A78BFA',
          checklist: '#22C55E',
          warning: '#F97316',
          metric: '#F472B6',
        },
      },
      typography: {
        headingFamily: 'var(--font-newsreader), Georgia, serif',
        bodyFamily: 'var(--font-geist-sans), Arial, sans-serif',
      },
      radius: '8px',
      shadow: '8px 8px 0 #3A3526',
    },
    style: {
      mode: 'dark',
    },
    labels: {
      evidence: 'Evidence',
      workshop: 'Workshop',
      library: 'Library',
    },
  },
  navigation: {
    primary: [
      { label: 'Library', routeKey: 'library' },
      { label: 'Pillars', routeKey: 'pillars' },
      { label: 'Sources', routeKey: 'sources' },
      { label: 'Workshop', routeKey: 'workshop' },
    ],
    secondary: [
      { label: 'Claims', routeKey: 'claims' },
      { label: 'Glossary', routeKey: 'glossary' },
      { label: 'Themes', routeKey: 'themes' },
      { label: 'Search', routeKey: 'search' },
    ],
  },
  home: {
    eyebrow: 'Creator operating system',
    headline: 'Build a repeatable practice from what already works.',
    summary: 'This preview manifest models a structured creator hub: principles, evidence, claims, vocabulary, themes, and a guided workshop.',
    featuredNodeIds: ['node_offer_lens', 'node_daily_capture', 'node_evidence_loop'],
    featuredPillarIds: ['pillar-positioning', 'pillar-production', 'pillar-trust'],
  },
  stats: {
    nodeCount: 6,
    pillarCount: 3,
    sourceCount: 3,
    segmentCount: 8,
    claimCount: 6,
    glossaryCount: 8,
  },
  nodes: [
    {
      id: 'node_offer_lens',
      slug: 'offer-lens',
      type: 'principle',
      title: 'Use an offer lens before writing',
      summary: 'Clarify who the work helps, what result it creates, and why now matters.',
      body: 'Strong creator strategy starts by naming the audience, the painful job, and the measurable outcome before choosing a format.',
      pillarIds: ['pillar-positioning'],
      themeIds: ['theme-demand', 'theme-clarity'],
      claimIds: ['claim-specificity-builds-trust'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-audience-job' }],
    },
    {
      id: 'node_daily_capture',
      slug: 'daily-capture',
      type: 'playbook',
      title: 'Capture proof daily',
      summary: 'Keep a lightweight log of objections, wins, questions, and exact language from the audience.',
      body: 'Daily capture turns scattered audience signals into a research base for scripts, offers, and examples.',
      pillarIds: ['pillar-production'],
      themeIds: ['theme-compounding'],
      claimIds: ['claim-capture-reduces-blank-page'],
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-capture-log' }],
    },
    {
      id: 'node_signal_stack',
      slug: 'signal-stack',
      type: 'metric',
      title: 'Read signal as a stack',
      summary: 'Combine retention, replies, saves, and sales context instead of optimizing one metric.',
      body: 'A single metric can reward shallow work; a signal stack keeps creative and business feedback in the same frame.',
      pillarIds: ['pillar-trust'],
      themeIds: ['theme-feedback'],
      claimIds: ['claim-one-metric-misleads'],
      evidence: [{ sourceId: 'src-analytics-walkthrough', segmentId: 'seg-signal-stack' }],
    },
    {
      id: 'node_evidence_loop',
      slug: 'evidence-loop',
      type: 'checklist',
      title: 'Close the evidence loop',
      summary: 'Attach a source, segment, or observed audience quote to any strategic claim.',
      body: 'The manual becomes more trustworthy when claims point back to concrete evidence instead of vague internal rationale.',
      pillarIds: ['pillar-trust'],
      themeIds: ['theme-feedback', 'theme-clarity'],
      claimIds: ['claim-evidence-improves-decisions'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-proof-before-polish' }],
    },
    {
      id: 'node-simple-promise',
      slug: 'simple-promise',
      type: 'example',
      title: 'Write the simple promise',
      summary: 'Turn the strategy into one plain sentence a reader could repeat.',
      body: 'A simple promise trades cleverness for memory. It states the result, audience, and mechanism without extra framing.',
      pillarIds: ['pillar-positioning'],
      themeIds: ['theme-demand', 'theme-clarity'],
      claimIds: ['claim-specificity-builds-trust'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-simple-promise' }],
    },
    {
      id: 'node-format-drift',
      slug: 'format-drift',
      type: 'warning',
      title: 'Avoid format drift',
      summary: 'Do not change formats so often that the audience cannot learn what to expect.',
      body: 'Experimentation works best inside a recognizable container: a stable promise, recurring segment, or consistent problem space.',
      pillarIds: ['pillar-production'],
      themeIds: ['theme-compounding'],
      claimIds: ['claim-consistency-builds-memory'],
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-format-drift' }],
    },
  ],
  pillars: [
    {
      id: 'pillar-positioning',
      slug: 'positioning',
      title: 'Positioning',
      summary: 'Define the audience, promise, and point of view before scaling output.',
      description: 'Positioning keeps the manual anchored in a specific audience problem and a recognizable promise.',
      sections: [
        { title: 'The operating question', body: 'Who is this for, what progress do they want, and why should this creator be the one to help?' },
        { title: 'The practical move', body: 'Force the idea through a concrete audience job before writing hooks, offers, or page copy.' },
      ],
      nodeIds: ['node_offer_lens', 'node-simple-promise'],
      claimIds: ['claim-specificity-builds-trust'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-audience-job' }],
    },
    {
      id: 'pillar-production',
      slug: 'production',
      title: 'Production',
      summary: 'Build a repeatable system for capturing, shaping, and shipping useful ideas.',
      description: 'Production covers the cadence, source material, and constraints that make publishing sustainable.',
      sections: [
        { title: 'The operating question', body: 'What repeatable inputs make output easier instead of forcing every piece to start from zero?' },
        { title: 'The practical move', body: 'Capture audience language daily, then review it weekly for promises, objections, and proof.' },
      ],
      nodeIds: ['node_daily_capture', 'node-format-drift'],
      claimIds: ['claim-capture-reduces-blank-page', 'claim-consistency-builds-memory'],
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-capture-log' }],
    },
    {
      id: 'pillar-trust',
      slug: 'trust',
      title: 'Trust',
      summary: 'Tie claims to evidence and let audience feedback refine the system.',
      description: 'Trust turns content from opinion into a documented practice with visible reasoning.',
      sections: [
        { title: 'The operating question', body: 'Which claims should the reader be able to audit without guessing where they came from?' },
        { title: 'The practical move', body: 'Attach evidence to the claims that shape strategy, positioning, and implementation decisions.' },
      ],
      nodeIds: ['node_signal_stack', 'node_evidence_loop'],
      claimIds: ['claim-one-metric-misleads', 'claim-evidence-improves-decisions'],
      evidence: [{ sourceId: 'src-analytics-walkthrough', segmentId: 'seg-signal-stack' }],
    },
  ],
  sources: [
    {
      id: 'src-positioning-roundtable',
      title: 'Positioning Roundtable',
      creatorName: 'Preview Creator',
      platform: 'youtube',
      youtubeId: 'dQw4w9WgXcQ',
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
      publishedAt: '2026-01-10T12:00:00.000Z',
      durationSec: 1840,
      summary: 'A session on turning market observations into a clear creator promise.',
      segmentIds: ['seg-audience-job', 'seg-simple-promise', 'seg-proof-before-polish'],
    },
    {
      id: 'src-workshop-notes',
      title: 'Creator Workshop Notes',
      creatorName: 'Preview Creator',
      platform: 'workshop',
      youtubeId: null,
      url: 'https://example.com/workshop-notes',
      publishedAt: '2026-02-05T12:00:00.000Z',
      durationSec: 2700,
      summary: 'A guided workshop on repeatable capture and production routines.',
      segmentIds: ['seg-capture-log', 'seg-format-drift', 'seg-weekly-review'],
    },
    {
      id: 'src-analytics-walkthrough',
      title: 'Audience Signal Walkthrough',
      creatorName: 'Preview Creator',
      platform: 'youtube',
      youtubeId: 'oHg5SJYRHA0',
      url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
      thumbnailUrl: 'https://i.ytimg.com/vi/oHg5SJYRHA0/hqdefault.jpg',
      publishedAt: '2026-03-15T12:00:00.000Z',
      durationSec: 2105,
      summary: 'A practical walkthrough for interpreting audience behavior without chasing vanity metrics.',
      segmentIds: ['seg-signal-stack', 'seg-sales-context'],
    },
  ],
  segments: [
    {
      id: 'seg-audience-job',
      sourceId: 'src-positioning-roundtable',
      slug: 'audience-job',
      title: 'Name the audience job',
      summary: 'The promise gets sharper when the audience job is concrete.',
      timestampStart: 125,
      timestampEnd: 248,
      transcriptExcerpt: 'Start with the job the audience is hiring the content to do, then pick the angle.',
      nodeIds: ['node_offer_lens'],
      claimIds: ['claim-specificity-builds-trust'],
    },
    {
      id: 'seg-simple-promise',
      sourceId: 'src-positioning-roundtable',
      slug: 'simple-promise',
      title: 'Compress the promise',
      summary: 'A repeatable sentence makes the strategy easier to share.',
      timestampStart: 412,
      timestampEnd: 501,
      transcriptExcerpt: 'If the promise takes a paragraph, the audience will not carry it with them.',
      nodeIds: ['node-simple-promise'],
      claimIds: ['claim-specificity-builds-trust'],
    },
    {
      id: 'seg-proof-before-polish',
      sourceId: 'src-positioning-roundtable',
      slug: 'proof-before-polish',
      title: 'Proof before polish',
      summary: 'Evidence should lead claims before design and copy polish.',
      timestampStart: 788,
      timestampEnd: 872,
      transcriptExcerpt: 'Before polishing the page, make the proof visible enough that the claim can be audited.',
      nodeIds: ['node_evidence_loop'],
      claimIds: ['claim-evidence-improves-decisions'],
    },
    {
      id: 'seg-capture-log',
      sourceId: 'src-workshop-notes',
      slug: 'capture-log',
      title: 'Keep a capture log',
      summary: 'A daily log keeps raw audience language available for future content.',
      timestampStart: 95,
      timestampEnd: 210,
      transcriptExcerpt: 'The capture log is not a diary; it is an input system for better decisions.',
      nodeIds: ['node_daily_capture'],
      claimIds: ['claim-capture-reduces-blank-page'],
    },
    {
      id: 'seg-format-drift',
      sourceId: 'src-workshop-notes',
      slug: 'format-drift',
      title: 'Constrain format changes',
      summary: 'Frequent format changes make it harder to build audience memory.',
      timestampStart: 602,
      timestampEnd: 690,
      transcriptExcerpt: 'Change the experiment, not the entire container, or the feedback becomes noisy.',
      nodeIds: ['node-format-drift'],
      claimIds: ['claim-consistency-builds-memory'],
    },
    {
      id: 'seg-weekly-review',
      sourceId: 'src-workshop-notes',
      slug: 'weekly-review',
      title: 'Review the week',
      summary: 'Weekly review turns captured inputs into next actions.',
      timestampStart: 1220,
      timestampEnd: 1348,
      transcriptExcerpt: 'Once a week, sort the log into themes, promises, objections, and proof.',
      nodeIds: ['node_daily_capture', 'node_evidence_loop'],
      claimIds: ['claim-capture-reduces-blank-page', 'claim-evidence-improves-decisions'],
    },
    {
      id: 'seg-signal-stack',
      sourceId: 'src-analytics-walkthrough',
      slug: 'signal-stack',
      title: 'Use a signal stack',
      summary: 'Retention, saves, replies, and sales context answer different questions.',
      timestampStart: 333,
      timestampEnd: 446,
      transcriptExcerpt: 'One metric can tell you what happened, but the stack tells you what to do next.',
      nodeIds: ['node_signal_stack'],
      claimIds: ['claim-one-metric-misleads'],
    },
    {
      id: 'seg-sales-context',
      sourceId: 'src-analytics-walkthrough',
      slug: 'sales-context',
      title: 'Add sales context',
      summary: 'Business outcomes help distinguish attention from demand.',
      timestampStart: 960,
      timestampEnd: 1040,
      transcriptExcerpt: 'A popular idea becomes strategic when it connects to a real audience decision.',
      nodeIds: ['node_offer_lens', 'node_signal_stack'],
      claimIds: ['claim-specificity-builds-trust', 'claim-one-metric-misleads'],
    },
  ],
  claims: [
    {
      id: 'claim-specificity-builds-trust',
      title: 'Specificity builds trust',
      statement: 'Specific audience and outcome language is easier to evaluate than broad inspiration.',
      confidence: 'strong',
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-audience-job' }],
      relatedNodeIds: ['node_offer_lens', 'node-simple-promise'],
    },
    {
      id: 'claim-capture-reduces-blank-page',
      title: 'Capture reduces blank-page work',
      statement: 'A live capture log gives creators concrete material before ideation begins.',
      confidence: 'strong',
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-capture-log' }],
      relatedNodeIds: ['node_daily_capture'],
    },
    {
      id: 'claim-one-metric-misleads',
      title: 'One metric can mislead',
      statement: 'Single-metric optimization can hide whether content is creating the intended audience action.',
      confidence: 'moderate',
      evidence: [{ sourceId: 'src-analytics-walkthrough', segmentId: 'seg-signal-stack' }],
      relatedNodeIds: ['node_signal_stack'],
    },
    {
      id: 'claim-evidence-improves-decisions',
      title: 'Evidence improves decisions',
      statement: 'Claims connected to source evidence are easier to review, revise, and trust.',
      confidence: 'strong',
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-proof-before-polish' }],
      relatedNodeIds: ['node_evidence_loop'],
    },
    {
      id: 'claim-consistency-builds-memory',
      title: 'Consistency builds memory',
      statement: 'Stable formats help the audience understand what kind of value to expect.',
      confidence: 'moderate',
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-format-drift' }],
      relatedNodeIds: ['node-format-drift'],
    },
    {
      id: 'claim-review-compounds-learning',
      title: 'Review compounds learning',
      statement: 'A regular review loop converts raw publishing feedback into reusable creative assets.',
      confidence: 'developing',
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-weekly-review' }],
      relatedNodeIds: ['node_daily_capture', 'node_evidence_loop'],
    },
  ],
  glossary: [
    { id: 'gloss-offer-lens', term: 'Offer lens', slug: 'offer-lens', definition: 'A framing habit that connects content to a specific audience result.', relatedNodeIds: ['node_offer_lens'] },
    { id: 'gloss-capture-log', term: 'Capture log', slug: 'capture-log', definition: 'A daily record of audience questions, objections, wins, and examples.', relatedNodeIds: ['node_daily_capture'] },
    { id: 'gloss-signal-stack', term: 'Signal stack', slug: 'signal-stack', definition: 'A grouped reading of metrics that balances attention, trust, and business context.', relatedNodeIds: ['node_signal_stack'] },
    { id: 'gloss-proof-point', term: 'Proof point', slug: 'proof-point', definition: 'A source-backed detail used to support a claim or recommendation.', relatedNodeIds: ['node_evidence_loop'] },
    { id: 'gloss-simple-promise', term: 'Simple promise', slug: 'simple-promise', definition: 'A plain-language statement of audience, outcome, and mechanism.', relatedNodeIds: ['node-simple-promise'] },
    { id: 'gloss-format-drift', term: 'Format drift', slug: 'format-drift', definition: 'The loss of audience memory caused by changing creative containers too often.', relatedNodeIds: ['node-format-drift'] },
    { id: 'gloss-audience-job', term: 'Audience job', slug: 'audience-job', definition: 'The task or progress a viewer hopes the content will help them make.', relatedNodeIds: ['node_offer_lens'] },
    { id: 'gloss-review-loop', term: 'Review loop', slug: 'review-loop', definition: 'A recurring process for turning feedback into decisions and next experiments.', relatedNodeIds: ['node_daily_capture', 'node_evidence_loop'] },
  ],
  themes: [
    {
      id: 'theme-demand',
      slug: 'demand',
      title: 'Demand',
      summary: 'The audience problem and motivation behind the work.',
      nodeIds: ['node_offer_lens', 'node-simple-promise'],
      pillarIds: ['pillar-positioning'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-audience-job' }],
    },
    {
      id: 'theme-clarity',
      slug: 'clarity',
      title: 'Clarity',
      summary: 'The language and proof that make the creator promise easy to understand.',
      nodeIds: ['node_offer_lens', 'node_evidence_loop', 'node-simple-promise'],
      pillarIds: ['pillar-positioning', 'pillar-trust'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-simple-promise' }],
    },
    {
      id: 'theme-compounding',
      slug: 'compounding',
      title: 'Compounding',
      summary: 'The routines that make each publishing cycle improve the next one.',
      nodeIds: ['node_daily_capture', 'node-format-drift'],
      pillarIds: ['pillar-production'],
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-weekly-review' }],
    },
    {
      id: 'theme-feedback',
      slug: 'feedback',
      title: 'Feedback',
      summary: 'The signals and review practices that refine decisions over time.',
      nodeIds: ['node_signal_stack', 'node_evidence_loop'],
      pillarIds: ['pillar-trust'],
      evidence: [{ sourceId: 'src-analytics-walkthrough', segmentId: 'seg-signal-stack' }],
    },
  ],
  workshop: [
    {
      id: 'stage-map-audience',
      slug: 'map-audience',
      title: 'Map the audience job',
      summary: 'Define the audience, current pain, and desired progress.',
      objective: 'Leave with one concrete audience job and three proof inputs.',
      steps: [
        { title: 'Choose the audience', body: 'Name the specific reader, viewer, or buyer this manual serves.' },
        { title: 'List the progress', body: 'Write what they want to accomplish and what blocks them today.' },
      ],
      nodeIds: ['node_offer_lens'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-audience-job' }],
    },
    {
      id: 'stage-write-promise',
      slug: 'write-promise',
      title: 'Write the simple promise',
      summary: 'Compress the strategy into a sentence the audience can remember.',
      objective: 'Draft a direct promise with audience, result, and mechanism.',
      steps: [
        { title: 'Draft plainly', body: 'Use everyday language before adding style.' },
        { title: 'Remove abstractions', body: 'Replace vague nouns with observable outcomes.' },
      ],
      nodeIds: ['node-simple-promise'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-simple-promise' }],
    },
    {
      id: 'stage-build-capture',
      slug: 'build-capture',
      title: 'Build the capture system',
      summary: 'Create a repeatable place to collect proof, questions, objections, and examples.',
      objective: 'Set up a daily capture routine that feeds future content.',
      steps: [
        { title: 'Create buckets', body: 'Track questions, proof, objections, examples, and phrases.' },
        { title: 'Schedule review', body: 'Reserve one weekly session to turn inputs into decisions.' },
      ],
      nodeIds: ['node_daily_capture'],
      evidence: [{ sourceId: 'src-workshop-notes', segmentId: 'seg-capture-log' }],
    },
    {
      id: 'stage-audit-evidence',
      slug: 'audit-evidence',
      title: 'Audit the evidence loop',
      summary: 'Check that important claims link back to usable source material.',
      objective: 'Identify unsupported claims and attach the best available evidence.',
      steps: [
        { title: 'List claims', body: 'Write each strategic claim as a sentence.' },
        { title: 'Attach support', body: 'Connect the claim to a source, segment, or audience observation.' },
      ],
      nodeIds: ['node_evidence_loop', 'node_signal_stack'],
      evidence: [{ sourceId: 'src-positioning-roundtable', segmentId: 'seg-proof-before-polish' }],
    },
  ],
  search: [
    { id: 'search-node-offer-lens', type: 'node', recordId: 'node_offer_lens', slug: 'offer-lens', title: 'Use an offer lens before writing', summary: 'Clarify audience, result, and urgency.', body: 'audience outcome offer positioning', keywords: ['offer', 'audience'] },
    { id: 'search-node-capture', type: 'node', recordId: 'node_daily_capture', slug: 'daily-capture', title: 'Capture proof daily', summary: 'Keep a lightweight log of audience signals.', body: 'capture log proof production', keywords: ['capture', 'proof'] },
    { id: 'search-pillar-positioning', type: 'pillar', recordId: 'pillar-positioning', slug: 'positioning', title: 'Positioning', summary: 'Define audience, promise, and point of view.', body: 'audience promise clarity' },
    { id: 'search-pillar-production', type: 'pillar', recordId: 'pillar-production', slug: 'production', title: 'Production', summary: 'Build a repeatable content system.', body: 'cadence capture shipping' },
    { id: 'search-source-positioning', type: 'source', recordId: 'src-positioning-roundtable', title: 'Positioning Roundtable', summary: 'A source video about market observations and creator promises.', body: 'source evidence audience job' },
    { id: 'search-source-analytics', type: 'source', recordId: 'src-analytics-walkthrough', title: 'Audience Signal Walkthrough', summary: 'A source video about reading audience behavior.', body: 'analytics retention saves replies sales' },
    { id: 'search-segment-signal-stack', type: 'segment', recordId: 'seg-signal-stack', slug: 'signal-stack', title: 'Use a signal stack', summary: 'Retention, saves, replies, and sales context answer different questions.', body: 'metrics signal stack feedback' },
    { id: 'search-segment-capture-log', type: 'segment', recordId: 'seg-capture-log', slug: 'capture-log', title: 'Keep a capture log', summary: 'A daily log preserves raw audience language.', body: 'capture log audience language' },
    { id: 'search-claim-specificity', type: 'claim', recordId: 'claim-specificity-builds-trust', title: 'Specificity builds trust', summary: 'Specific language is easier to evaluate.', body: 'specificity trust audience outcome' },
    { id: 'search-claim-evidence', type: 'claim', recordId: 'claim-evidence-improves-decisions', title: 'Evidence improves decisions', summary: 'Claims connected to evidence are easier to review.', body: 'evidence claims decisions' },
    { id: 'search-glossary-offer-lens', type: 'glossary', recordId: 'gloss-offer-lens', slug: 'offer-lens', title: 'Offer lens', summary: 'Content framing connected to a specific audience result.', body: 'glossary offer audience result' },
    { id: 'search-glossary-signal-stack', type: 'glossary', recordId: 'gloss-signal-stack', slug: 'signal-stack', title: 'Signal stack', summary: 'Grouped metrics for attention, trust, and business context.', body: 'glossary metrics signal' },
    { id: 'search-theme-clarity', type: 'theme', recordId: 'theme-clarity', slug: 'clarity', title: 'Clarity', summary: 'Language and proof that make the promise understandable.', body: 'clarity promise proof language' },
    { id: 'search-theme-feedback', type: 'theme', recordId: 'theme-feedback', slug: 'feedback', title: 'Feedback', summary: 'Signals and review practices that refine decisions.', body: 'feedback review signal' },
    { id: 'search-workshop-map', type: 'workshop', recordId: 'stage-map-audience', slug: 'map-audience', title: 'Map the audience job', summary: 'Define audience, pain, and desired progress.', body: 'workshop audience job' },
    { id: 'search-workshop-audit', type: 'workshop', recordId: 'stage-audit-evidence', slug: 'audit-evidence', title: 'Audit the evidence loop', summary: 'Attach support to important claims.', body: 'workshop evidence claims audit' },
  ],
};
